// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ2WTO-WJsII1sRh2StrTm-Bul7EmxjXM',
    appId: '1:736538134359:web:d0f119897a1f5cab39e012',
    messagingSenderId: '736538134359',
    projectId: 'dundgovi-5b4ca',
    authDomain: 'dundgovi-5b4ca.firebaseapp.com',
    storageBucket: 'dundgovi-5b4ca.appspot.com',
    measurementId: 'G-68CTCKR1FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8VWzyYZWr_-Txt6XWOYY2xNHPQ_FptWU',
    appId: '1:736538134359:android:9eddbf6c5cc8b09239e012',
    messagingSenderId: '736538134359',
    projectId: 'dundgovi-5b4ca',
    storageBucket: 'dundgovi-5b4ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc7iUarxpSRo8WI-adpMINbbemVPRbeN4',
    appId: '1:736538134359:ios:c0ac57b42dcc11b539e012',
    messagingSenderId: '736538134359',
    projectId: 'dundgovi-5b4ca',
    storageBucket: 'dundgovi-5b4ca.appspot.com',
    androidClientId: '736538134359-mvdu42ts6h5lldmb2vlqe60k0bivvfn6.apps.googleusercontent.com',
    iosClientId: '736538134359-efs9jpua0b9m8qrtpsad3makk6k8aa48.apps.googleusercontent.com',
    iosBundleId: 'com.ihotel.dundgovi',
  );
}
